#!/usr/bin/env bash
# ---------------------------------------------------------
# Script para verificar, criar e ativar um ambiente virtual Python
# ---------------------------------------------------------

set -e

VENV_DIR=".env"

if ! command -v python3 &>/dev/null; then
  echo "❌ Python3 doesn't exist. Install before continue."
  exit 1
fi

if [ -d "$VENV_DIR" ]; then
  echo "✅ Venv already exist: $VENV_DIR"
else
  echo "⚙️ Creating venv: $VENV_DIR ..."
  python3 -m venv "$VENV_DIR"
  echo "✅ Venv created successfully"

  echo "🚀 Activating venv ..."
  source "$VENV_DIR/bin/activate"

  pip install simple-term-menu
fi

if [ -f "$VENV_DIR/bin/activate" ]; then
  echo "🚀 Activating venv ..."
  source "$VENV_DIR/bin/activate"
  echo "✅ Venv activated!"

else
  echo "❌ Venv not found $VENV_DIR/bin/activate"
  exit 1
fi

current_path=$(pwd)
echo $current_path

python3 $current_path/utils/installer_manager.py

